version: '3.7'
services:
  db:
    image: postgres:12-alpine
    container_name: PostgreSQL-12
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - postgre-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - postgre-network
  
networks:
  postgre-network:
    driver: bridge
